### ISSUE TITLE
Update the repository with Open Source Examples

### ISSUE THREAD

**Issue by fbrace1** [fbrace1/Senior-Experience-Project#1]
We need to update the repository with the Open Source Exmples that we were thinking about adding so we have them all in one place.

**Comment by MaxGuH** [comment]
So since the code in that open source example is different, can we have 2 folders with different "projects" at the same time? Or just create it as a fork?

**Comment by fbrace1** [comment]
Yeah, I would just add it as it's own .py file or folder if necessary.   We can integrate the code later.  Good first step to have all the examples together.   If you feel comfortable creating a fork you could do that as well.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Max Guzarevich ***@***.***>
Sent: Monday, February 12, 2024 12:14:44 PM
To: fbrace1/Senior-Experience-Project ***@***.***>
Cc: Brace, Fred ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [fbrace1/Senior-Experience-Project] Update the repository with Open Source Examples (Issue #1)


NOTICE: This email originated from outside the University. Please exercise caution when replying or opening links and attachments.


So since the code in that open source example is different, can we have 2 folders with different "projects" at the same time? Or just create it as a fork?

**Comment by MaxGuH** [comment]
For now added as a fork since there is multiple .py files. 
https://github.com/MaxGuH/Senior-Experience-Project/tree/main

**Comment by fbrace1** [comment]
Sounds good. Ill take a look here in a bit!

**Comment by fbrace1** [comment]
Do you think we can close this issue?

**Comment by MaxGuH** [comment]
Yes.

**Comment by fbrace1** [comment]
Issue Closed!
